name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag azure-cli:latest
    - name: Docker check
      run: |
        docker image ls
        docker manifest inspect azure-cli:latest
        docker image inspect azure-cli:latest
